### ISSUE TITLE
Double underline

### ISSUE THREAD

**Issue by simurai** [lee-dohm/red-wavy-underline#10]
In Atom `1.13` there is a double underline. The default one and the red-wavy-underline:

<img width="180" alt="shadow-dom-changes_360" src="https://cloud.githubusercontent.com/assets/378023/19507611/15f4b6ac-960f-11e6-87f4-2ee278e7900c.png">

**Comment by lexicalunit** [comment]
Seeing this as well in Atom `v1.13.0-beta2`.
<img width="265" alt="screen shot 2016-11-15 at 10 54 23 am" src="https://cloud.githubusercontent.com/assets/1903876/20315062/0dfc61d4-ab22-11e6-995a-2f5b5ea54b2c.png">

**Comment by lexicalunit** [comment]
This seems to fix it though there may be a better way that avoids the use of `!important` somehow.

```
diff --git a/styles/red-wavy-underline.less b/styles/red-wavy-underline.less
index f747341..54f1dbe 100644
--- a/styles/red-wavy-underline.less
+++ b/styles/red-wavy-underline.less
@@ -1,6 +1,6 @@
 .red-wavy-underline {
   background: url('atom://red-wavy-underline/assets/red-wavy-underline.png') bottom repeat-x;
-  border-bottom: none;
+  border-bottom: none !important;
   margin-top: 2px;
 }
```

**Comment by lee-dohm** [comment]
@lexicalunit Which theme are you using to reproduce this? I don't see it using red-wavy-underline v0.3.1, Atom v1.13.0-beta3 and the One Light UI and Syntax themes.

**Comment by lexicalunit** [comment]
I'm using the [Native UI Theme](https://atom.io/themes/native-ui) and the [Base16 Syntax Theme](https://atom.io/packages/base16-syntax). I switched over to using One Light for UI and Syntax theme and then reloaded Atom but I still see the double underline in that case.
<img width="245" alt="screen shot 2016-11-15 at 12 28 08 pm" src="https://cloud.githubusercontent.com/assets/1903876/20318254/160c910c-ab2f-11e6-9d89-8a09bd5d0554.png">
I also removed everything from my `styles.less` just in case. Other packages I have installed:

```
Community Packages (68) /Users/lexicalunit/.atom/packages
├── MagicPython@0.5.17
├── activate-power-mode@1.1.0
├── aesthetic-ui@2.0.0
├── atom-beautify@0.29.13
├── atom-isort@1.2.1
├── atom-language-avro@0.0.13
├── autocomplete-python@1.8.12
├── autoupdate-packages@1.3.1
├── base16-syntax@1.7.0
├── column-select@0.2.0
├── cursor-indicator@1.2.7
├── event-watch@4.0.0
├── file-icons@1.7.25
├── force-tab@0.2.0
├── format-shell@1.0.4
├── highlight-selected@0.11.2
├── indent-guide-improved@1.4.11
├── jumpy@3.1.3
├── language-applescript@0.3.0
├── language-babel@2.49.2
├── language-cmake@0.2.0
├── language-diff@0.6.0
├── language-docker@1.1.7
├── language-groovy@0.6.0
├── language-json@0.18.3
├── language-latex@1.0.0
├── language-restructuredtext@1.0.1
├── language-rust@0.4.8
├── language-scala@1.1.8
├── line-length-break@0.4.0
├── linter@1.11.19
├── linter-clang@3.4.4
├── linter-coffeelint@1.2.0
├── linter-csslint@1.3.3
├── linter-docker@0.1.2
├── linter-erb@1.0.2
├── linter-eslint@8.0.0
├── linter-flake8@2.0.2
├── linter-jsonlint@1.3.0
├── linter-just-say-no@0.7.0
├── linter-raml@1.0.1
├── linter-rubocop@0.5.0
├── linter-shellcheck@1.4.1
├── linter-tidy@2.3.0
├── linter-write-good@0.8.0
├── markdown-toc@0.4.1
├── minimap@4.26.3
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.4.0
├── minimap-selection@4.4.0
├── multi-wrap-guide@0.28.2
├── native-ui@0.19.1
├── no-title-bar@0.1.0
├── nvatom@0.11.0
├── pretty-json@1.6.1
├── python-yapf@0.13.0
├── raml@0.2.0
├── red-wavy-underline@0.3.1
├── script@3.11.1
├── set-syntax@0.3.2
├── soft-wrap-indicator@1.0.1
├── sort-lines@0.14.0
├── standard-formatter@2.6.0
├── tab-control@0.6.9
├── tabs-to-spaces@1.0.2
├── toggle-quotes@1.0.0
└── trailing-spaces@0.3.2
```

**Comment by lee-dohm** [comment]
Ah ok ... I import the red-wavy-underline CSS into my `styles.less` for using in other places too. That's what boosts the rule on my machine. Will test to see if #11 fixes it.

**Comment by lee-dohm** [comment]
Thanks very much for your help @lexicalunit :grinning: v0.3.2 should fix it for you. Let me know if it doesn't!
